### ISSUE TITLE
why dont you run the POR circuit from the 3.3V supply? :P

### ISSUE THREAD

**Issue by urjaman** [yifanlu/psvsd#1]
Save a resistor, and it'll actually do the reset off when the 3.3V goes up...

(Not a big issue, but github doesnt have that good messaging... feel free to close.)

**Comment by yifanlu** [comment]
So the specs require that you hold reset low for 1us _after_ device powerup (which is 400us). Now if I have the LDO output directly to resetn, then there is no guarantee of the 1us hold. The RC circuit is there to ensure that this is the case. Quick calculation shows that since Vita's Vdd is a 4V output, we need a 165k/100k voltage divider to get ~2.5V output (which is a little above V_IH). The 0.1uF capacitor will make the ramp-up time ~30ms, which is good enough for the required 1us hold. Hope that makes sense.

**Comment by urjaman** [comment]
I meant you could run R3 from VDD33 instead of VDD5 and remove R2.
This would give ... 10ms RC time with the current values, which again would be just fine.
(EDIT: I assume you know how that traditional POR circuit works... C6 starts at 0V because VDD33 starts at 0V...)

**Comment by yifanlu** [comment]
I see what you mean, but as long as it's not a problem, I don't think it's worth changing the circuit. The resistor is plenty cheap, so cost isn't an issue. And it's worth saving some current draw.
